export const CREATE_POST_REQUEST = "CREATE_POST_REQUEST";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_FAILURE = "CREATE_POST_FAILURE";

export const CREATE_REPLY_POST_REQUEST = "CREATE_REPLY_POST_REQUEST";
export const CREATE_REPLY_POST_SUCCESS = "CREATE_REPLY_POST_SUCCESS";
export const CREATE_REPLY_POST_FAILURE = "CREATE_REPLY_POST_FAILURE";

export const FIND_POST_BY_ID_REQUEST = "FIND_POST_BY_ID_REQUEST";
export const FIND_POST_BY_ID_SUCCESS = "FIND_POST_BY_ID_SUCCESS";
export const FIND_POST_BY_ID_FAILURE = "FIND_POST_BY_ID_FAILURE";

export const LIKE_POST_REQUEST = "LIKE_POST_REQUEST";
export const LIKE_POST_SUCCESS = "LIKE_POST_SUCCESS";
export const LIKE_POST_FAILURE = "LIKE_POST_FAILURE";

export const REPOST_REQUEST = "REPOST_REQUEST";
export const REPOST_SUCCESS = "REPOST_SUCCESS";
export const REPOST_FAILURE = "REPOST_FAILURE";

export const DELETE_POST_REQUEST = "DELETE_POST_REQUEST";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_FAILURE = "DELETE_POST_FAILURE";

export const FIND_ALL_REPLY_POSTS_BY_PARENT_POST_ID_REQUEST =
  "FIND_ALL_REPLY_POSTS_BY_PARENT_POST_ID_REQUEST";
export const FIND_ALL_REPLY_POSTS_BY_PARENT_POST_ID_SUCCESS =
  "FIND_ALL_REPLY_POSTS_BY_PARENT_POST_ID_SUCCESS";
export const FIND_ALL_REPLY_POSTS_BY_PARENT_POST_ID_FAILURE =
  "FIND_ALL_REPLY_POSTS_BY_PARENT_POST_ID_FAILURE";

export const FIND_ALL_FOLLOWING_USER_POSTS_REQUEST =
  "FIND_ALL_FOLLOWING_USER_POSTS_REQUEST";
export const FIND_ALL_FOLLOWING_USER_POSTS_SUCCESS =
  "FIND_ALL_FOLLOWING_USER_POSTS_SUCCESS";
export const FIND_ALL_FOLLOWING_USER_POSTS_FAILURE =
  "FIND_ALL_FOLLOWING_USER_POSTS_FAILURE";

export const FIND_ALL_POSTS_REQUEST = "FIND_ALL_POSTS_REQUEST";
export const FIND_ALL_POSTS_SUCCESS = "FIND_ALL_POSTS_SUCCESS";
export const FIND_ALL_POSTS_FAILURE = "FIND_ALL_USER_FOLLOWING_POSTS_FAILURE";

export const FIND_ALL_USER_POSTS_REQUEST = "FIND_ALL_USER_POSTS_REQUEST";
export const FIND_ALL_USER_POSTS_SUCCESS = "FIND_ALL_USER_POSTS_SUCCESS";
export const FIND_ALL_USER_POSTS_FAILURE = "FIND_ALL_USER_POSTS_FAILURE";

export const FIND_ALL_USER_REPLY_POSTS_REQUEST =
  "FIND_ALL_USER_REPLY_POSTS_REQUEST";
export const FIND_ALL_USER_REPLY_POSTS_SUCCESS =
  "FIND_ALL_USER_REPLY_POSTS_SUCCESS";
export const FIND_ALL_USER_REPLY_POSTS_FAILURE =
  "FIND_ALL_USER_REPLY_POSTS_FAILURE";

export const FIND_ALL_USER_MEDIA_POSTS_REQUEST =
  "FIND_ALL_USER_MEDIA_POSTS_REQUEST";
export const FIND_ALL_USER_MEDIA_POSTS_SUCCESS =
  "FIND_ALL_USER_MEDIA_POSTS_SUCCESS";
export const FIND_ALL_USER_MEDIA_POSTS_FAILURE =
  "FIND_ALL_USER_MEDIA_POSTS_FAILURE";

export const FIND_ALL_USER_LIKED_POSTS_REQUEST =
  "FIND_ALL_USER_LIKED_POSTS_REQUEST";
export const FIND_ALL_USER_LIKED_POSTS_SUCCESS =
  "FIND_ALL_USER_LIKED_POSTS_SUCCESS";
export const FIND_ALL_USER_LIKED_POSTS_FAILURE =
  "FIND_ALL_USER_LIKED_POSTS_FAILURE";

export const CLEAR_POST_ERROR = "CLEAR_POST_ERROR";
