export const SIGN_UP_REQUEST = "SIGN_UP_REQUEST";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAILURE = "SIGN_UP_FAILURE";

export const SIGN_IN_REQUEST = "SIGN_IN_REQUEST";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_FAILURE = "SIGN_IN_FAILURE";

export const FIND_REQ_USER_REQUEST = "FIND_REQ_USER_REQUEST";
export const FIND_REQ_USER_SUCCESS = "FIND_REQ_USER_SUCCESS";
export const FIND_REQ_USER_FAILURE = "FIND_REQ_USER_FAILURE";

export const FIND_REQ_USER_BY_ID_REQUEST = "FIND_REQ_USER_BY_ID_REQUEST";
export const FIND_REQ_USER_BY_ID_SUCCESS = "FIND_REQ_USER_BY_ID_SUCCESS";
export const FIND_REQ_USER_BY_ID_FAILURE = "FIND_REQ_USER_BY_ID_FAILURE";

export const SEARCH_USER_REQUEST = "SEARCH_USER_REQUEST";
export const SEARCH_USER_SUCCESS = "SEARCH_USER_SUCCESS";
export const SEARCH_USER_FAILURE = "SEARCH_USER_FAILURE";

export const FOLLOW_USER_REQUEST = "FOLLOW_USER_REQUEST";
export const FOLLOW_USER_SUCCESS = "FOLLOW_USER_SUCCESS";
export const FOLLOW_USER_FAILURE = "FOLLOW_USER_FAILURE";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILURE = "UPDATE_USER_FAILURE";

export const CLEAR_USER_ERROR = "CLEAR_USER_ERROR";

export const SIGN_OUT = "SIGN_OUT";
